.create table Raspberrypi (gym_id: int, machine_id: int, user_id: int, repcount:int, weight: int, rep_time: string)

.create table Raspberrypi ingestion json mapping 'TestMapping1' '[{"column":"gym_id","path":"$.gym_id","datatype":"int"},
                                                                  {"column":"machine_id","path":"$.machine_id","datatype":"int"},
                                                                  {"column":"user_id","path":"$.user_id","datatype":"int"},
                                                                  {"column":"repcount","path":"$.rep_count","datatype":"int"},
                                                                  {"column":"weight","path":"$.weight","datatype":"int"},
                                                                  {"column":"reptime","path":"$.reptime","datatype":"string"}]'

